export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_AUTHORIZATION_DATA = 'SET_USER_AUTHORIZATION_DATA';
export const UPDATE_USER_BALANCE = 'UPDATE_USER_BALANCE';
export const SET_USERS_LIST = 'SET_USERS_LIST';
